### ISSUE TITLE
Hey Jeff

### ISSUE THREAD

**Issue by mrlooi** [Palmer-JC/Palmer-JC.github.io#1]
Hey Jeff, noticed your facial animation work on WebGL, I think it's really amazing. 

Are there any commits in the pipeline for adding this work into Babylon.js?

PS: Didn't know where else to reach you. Let me know if there's a better way to connect :)

**Comment by Palmer-JC** [comment]
No there are not, sorry.  For one thing, I am always improving it, and frequently breaking compatibility.  BJS does very hard to avoid that.

It is also very dependent on a MakeHuman / Blender work flow.  When this is not published, I can move stuff to different places.  No notifications or documentation changes.  No documentation at all except for in code.

I also do not have time to support others.
